import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
 const sidebars: SidebarsConfig = {
  guideSidebar: [
    'demo',
    {
      type: 'category',
      label: 'О приложениях',
      items: [
        {
          type: 'autogenerated',
          dirName: 'apps', // generate sidebar from the docs folder (or versioned_docs/<version>)
        },
      ]
    },
    {
      type: 'category',
      label: 'VK Bridge',
      items: [
        {
          type: 'autogenerated',
          dirName: 'vk-bridge', // generate sidebar from the docs folder (or versioned_docs/<version>)
        },
      ]
    },
  ],
  apiSidebar: [
    {
      label: 'API',
      type: 'category',
      link: { type: 'doc', id: 'api/index'},
      items: [
        { type: 'doc', id: 'api/index2'},
      ],
    }
  ],
}

export default sidebars;
